// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcedvlqhpiwjwbvzthym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZWR2bHFocGl3andidnp0aHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTE4ODgsImV4cCI6MjA2OTM4Nzg4OH0.udQ9UxbTrkH4vECe9xk9L4u0k7evL2Gzj6iEH6djp0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});